### ISSUE TITLE
unsupported model to partitioning 

### ISSUE THREAD

**Issue by windmaple** [Locutusque/TPU-Alignment#1]
Thx for putting this together for the GPU poor out there.

Gave your notebook a spin on Kaggle TPU, but hit the partitioning error:

```
trainable params: 7,241,732,096 || all params: 7,241,732,096 || trainable%: 100.0
device_ids [0 1 2 3 4 5 6 7]
mesh_shape (1, 8, 1)
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
Cell In[15], line 48
     46 print(f'mesh_shape', mesh_shape)
     47 mesh = Mesh(device_ids, mesh_shape, ('dp', 'fsdp', 'mp'))
---> 48 partition_module(model, mesh) # After this, the model is sharded between cores but still has the same API as if it was on single device. Neat.

File /kaggle/working/spmd_util.py:95, in partition_module(model, mesh, device, verbose)
     94 def partition_module(model, mesh, device=xm.xla_device(), verbose=False):
---> 95     partition_specs = find_rule(model)
     96     # rule = [(k, tuple([strkey2id.get(x) for x in v])) for k, v in partition_specs]
     97         
     98     # print(rule)
    100     for name, module in model.named_modules():

File /kaggle/working/spmd_util.py:86, in find_rule(model)
     84     if model.config.__class__ == config:
     85         return rule
---> 86 raise Exception("unsupported model to partitioning " + str(model.config.__class__))

Exception: unsupported model to partitioning <class 'transformers.models.mistral.configuration_mistral.MistralConfig'>
```

The only thing I changed is to add 2 prints for device_ids and mesh_shape. I remember trying out similar Kaggle notebooks (i.e., 
 [this one](https://www.kaggle.com/code/minhsienweng/tpu-train-mistral-7b-deberta-v3-detection?scriptVersionId=152465296)) but didn't get this. 

Any idea?

**Comment by Locutusque** [comment]
Could you publish the notebook you're using on Kaggle and link it here? This can help me rule out some suspicions.

**Comment by windmaple** [comment]
[Here](https://www.kaggle.com/code/wind1112/notebookf9b7896acd) it is.

**Comment by Locutusque** [comment]
> [Here](https://www.kaggle.com/code/wind1112/notebookf9b7896acd) it is.

On the first code cell, try uncommenting the "# !cp /kaggle/working/spmd_util.py . # From this repo: https://github.com/HeegyuKim/torch-xla-SPMD" line, and remove the curl command. The place that your cloning the spmd_util.py does not support the mistral architecture. Try this and tell me how it goes.

**Comment by windmaple** [comment]
Indeed. I curl'ed the SPMD utility from the other repo which turns out to be the issue.

Thanks for the quick response!
