### ISSUE TITLE
Support for LLama like models (Deepseek)

### ISSUE THREAD

**Issue by VatsaDev** [Locutusque/TPU-Alignment#11]
Considering that other repos like unsloth placed deepseek as possible due to the similarities in architecture between it and Llama.

Comparing how the repo supports LLama Mistral and Qwen, is deepseek possible?

**Comment by RD211** [comment]
I am currently training `deepseek-math-7b-instructl` with a modified version of this script. I am using v4-16 and it seems to work alright. I have to train in fp32 though cause for some reason it crashes at bf16. 
Did not test on kaggle though it should probably work there too.

I assume you are participating in the kaggle competition too? :)

**Comment by VatsaDev** [comment]
Yep AIMO :)

though, v3-8 and v2-8 tend to be diff for other libraries.

Is v4-16 branch/nb? would love to have that version

**Comment by RD211** [comment]
I believe the script is made especially for v3-8s so it should probably work directly on Kaggle and I would try it there first cause it should be good enough. By v4-16 I mean I am running it on TPU V4s and not on the V3s.

**Comment by VatsaDev** [comment]
K, but @RD211 what are your deepseek rules? like in the config?

**Comment by RD211** [comment]
I did not change anything in the `spmd_util.py` file. It should work as is.

**Comment by VatsaDev** [comment]
Thanks!

**Comment by Locutusque** [comment]
I will work on adding support for these language models this week.

**Comment by Locutusque** [comment]
Closing because llama-like models are already supported.
