### ISSUE TITLE
Axolotl

### ISSUE THREAD

**Issue by fakerybakery** [Locutusque/TPU-Alignment#4]
Hi,
Great project - do you know if there's any possibility of integrating this into Axolotl?
Thanks!

**Comment by Locutusque** [comment]
Hello, thanks for your interest! I'm not very fond with Axolotl, I typically write my on training scripts. You can try opening an issue linking to this on their repository, I'd be willing to collaborate with Axolotl's developers to implement TPU support.

**Comment by fakerybakery** [comment]
OK, thanks!
