### ISSUE TITLE
Incorrect implementation for calculating loss

### ISSUE THREAD

**Issue by IsNoobgrammer** [Locutusque/TPU-Alignment#6]
The way loss in our code is commonly used for Classifier models but not for text-generation models
thats the reason it seems that model was converging too fast.. 
[Transformers](https://github.com/huggingface/transformers/blob/main/src/transformers/trainer.py#L2886) is also calculating  loss similarly

will push a pr implementing it , if it works correctly 
You can see the difference in loss in the given figure
![image](https://github.com/Locutusque/TPU-Alignment/assets/112808251/a26a9a8d-8288-46a2-8293-e05a4a0a1e97)

**Comment by Locutusque** [comment]
Can you provide more information about this loss your talking about? Cross Entropy is typical for text generation.
