### ISSUE TITLE
[feature request] Add support for Google Gemma models

### ISSUE THREAD

**Issue by windmaple** [Locutusque/TPU-Alignment#7]
[Google Gemma](https://ai.google.dev/gemma/)

**Comment by Locutusque** [comment]
I'll work on adding support for Google Gemma this week. Expect it by Friday or Saturday.

**Comment by Locutusque** [comment]
I've been working on this, but seems to have sharding issues. I'll continue working on it. I'm unsure why Gemma is causing sharding issues.

**Comment by IsNoobgrammer** [comment]
> I have Implemented sharding and after testing (unaligning-gemma) will add a PR
> 
> ![image](https://private-user-images.githubusercontent.com/112808251/308887236-435e20c0-4ff7-4519-bc02-ec4f21655009.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyMDQyNDAsIm5iZiI6MTcwOTIwMzk0MCwicGF0aCI6Ii8xMTI4MDgyNTEvMzA4ODg3MjM2LTQzNWUyMGMwLTRmZjctNDUxOS1iYzAyLWVjNGYyMTY1NTAwOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyOVQxMDUyMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZWRkYzhhNjQ2MzllMjJiMGRhZDlmOWUzMTU3OGIxMDUxOWJhNmZmNmQ3YzE0MzRiM2Y2OGU4ODg4NjZmMDUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xHXyvLjZfwZl7YUftrY7wi3jIj3NAWH1NYMq2E1KBcE)

Even after through prompting and tests "gemma-7b-it" is downright bad  but implementation are working
