### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by francqz31** [Locutusque/TPU-Alignment#9]
I just have a quick question about preparing a dataset that is a bit unique not like other conversational datasets out there
it is lyrics dataset [lyrics.txt](https://github.com/Locutusque/TPU-Alignment/files/14516817/lyrics.txt) what should be the process?
should I annotate it or tokenize it outside then import it to your notebook for example or would the notebook handle it. and how even to tokenize a dataset like that.

Thanks in advance

**Comment by Locutusque** [comment]
Ignoring the fact that a language model trained on this unique dataset, you don't need to use the dataset classes shown in the notebook. All you really need to do is read the text directly from that file you attached.
